# Generated by Django 3.2.5 on 2022-07-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Code',
            new_name='code',
        ),
    ]
